# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from time import sleep

from PyQt5 import QtCore, QtGui, QtWidgets
from CrawlerMethod import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(828, 370)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setGeometry(QtCore.QRect(30, 10, 741, 291))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.URLsTextInput = QtWidgets.QPlainTextEdit(self.MainFrame)
        self.URLsTextInput.setGeometry(QtCore.QRect(120, 20, 561, 61))
        self.URLsTextInput.setPlainText("")
        self.URLsTextInput.setObjectName("URLsTextInput")
        self.URLLabel = QtWidgets.QLabel(self.MainFrame)
        self.URLLabel.setGeometry(QtCore.QRect(10, 20, 60, 16))
        self.URLLabel.setObjectName("URLLabel")
        self.PDFCheckBox = QtWidgets.QCheckBox(self.MainFrame)
        self.PDFCheckBox.setGeometry(QtCore.QRect(120, 90, 87, 20))
        self.PDFCheckBox.setObjectName("PDFCheckBox")
        self.DirPathInput = QtWidgets.QLineEdit(self.MainFrame)
        self.DirPathInput.setGeometry(QtCore.QRect(120, 130, 521, 21))
        self.DirPathInput.setObjectName("DirPathInput")
        self.DirPathButton = QtWidgets.QPushButton(self.MainFrame)
        self.DirPathButton.setGeometry(QtCore.QRect(640, 130, 41, 21))
        self.DirPathButton.setObjectName("DirPathButton")
        self.DirPathLable = QtWidgets.QLabel(self.MainFrame)
        self.DirPathLable.setGeometry(QtCore.QRect(9, 130, 91, 20))
        self.DirPathLable.setObjectName("DirPathLable")
        self.FileTypeLabel = QtWidgets.QLabel(self.MainFrame)
        self.FileTypeLabel.setGeometry(QtCore.QRect(10, 90, 91, 20))
        self.FileTypeLabel.setObjectName("FileTypeLabel")
        self.CrawlButton = QtWidgets.QPushButton(self.MainFrame)
        self.CrawlButton.setGeometry(QtCore.QRect(110, 220, 113, 32))
        self.CrawlButton.setObjectName("CrawlButton")
        self.DownloadButton = QtWidgets.QPushButton(self.MainFrame)
        self.DownloadButton.setGeometry(QtCore.QRect(220, 220, 113, 32))
        self.DownloadButton.setObjectName("DownloadButton")
        self.LabelNoFiles = QtWidgets.QLabel(self.MainFrame)
        self.LabelNoFiles.setGeometry(QtCore.QRect(120, 170, 521, 16))
        self.LabelNoFiles.setObjectName("LabelNoFiles")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 828, 24))
        self.menubar.setObjectName("menubar")
        self.menuCrawler = QtWidgets.QMenu(self.menubar)
        self.menuCrawler.setObjectName("menuCrawler")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCrawler.menuAction())

        self.retranslateUi(MainWindow)

        self.file_types_list = []

        self.PDFCheckBox.stateChanged.connect(self.pdf_check_state_changed)
        self.CrawlButton.clicked.connect(self.crawl)
        self.DownloadButton.clicked.connect(self.download)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.URLsTextInput.setPlaceholderText(_translate("MainWindow", "Enter your URLs here"))
        self.URLLabel.setText(_translate("MainWindow", "URLs"))
        self.PDFCheckBox.setText(_translate("MainWindow", ".pdf"))
        self.DirPathButton.setText(_translate("MainWindow", "..."))
        self.DirPathLable.setText(_translate("MainWindow", "Directory path"))
        self.FileTypeLabel.setText(_translate("MainWindow", "File types"))
        self.CrawlButton.setText(_translate("MainWindow", "Crawl"))
        self.DownloadButton.setText(_translate("MainWindow", "Download"))
        self.LabelNoFiles.setText(_translate("MainWindow", "Not thing found yet"))
        self.menuCrawler.setTitle(_translate("MainWindow", "Crawler"))

    def pdf_check_state_changed(self):
        if self.PDFCheckBox.isChecked():
            self.file_types_list.append(".pdf")
        else:
            self.file_types_list.remove(".pdf")

    def crawl(self):
        list_urls = self.URLsTextInput.toPlainText().splitlines()
        self.crawler = CrawlerMethod(list_urls, self.file_types_list, self.DirPathInput.text())
        self.LabelNoFiles.setText("Crawling!")

        self.crawler.find_all_clickable_links()
        self.LabelNoFiles.setText("Found "+ str(int(len(self.crawler.file_list))) + " files!")

    def download(self):
        print("Downloading")
        self.LabelNoFiles.setText("Downloading!")
        self.crawler.download()
        self.LabelNoFiles.setText("Downloaded!")



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
